name: photo_editing_app
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # pick images
  image_picker: ^0.6.7+17

  # crop images
  image_cropper: ^1.3.1

  cached_network_image: ^2.2.0+1

  image_editor: ^0.7.1
  
  extended_image:
    git:
      url: git://github.com/codenameakshay/extended_image.git

  photo_view: ^0.9.2

  gallery_saver: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true